server:
  port: 8088

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    connect-timeout: 5s
    timeout : 5s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 5s
